### ISSUE TITLE
Building and Testing with Docker Locally

### ISSUE THREAD

**Issue by gzhao408** [GoogleCloudPlatform/stackdriver-sandbox#163]
Bug: When building + running with Docker locally (i.e. per service) one might get this error: 

```
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```
For me, using the link to set up authentication and setting the env variable `GOOGLE_APPLICATION_CREDENTIALS` didn't fix this issue.

Solution:
1. build and tag the image `docker build . --tag gcr.io/[PROJECT-ID]/[IMAGE]`
2. configure docker (.docker/config.json file) using `gcloud auth configure-docker`
3. when using `docker run`, pass in some extra flags:
```
PORT=8080 && docker run \
-p 9090:${PORT} \
-e PORT=${PORT} \
-e K_SERVICE=dev \
-e K_CONFIGURATION=dev \
-e K_REVISION=dev-00001 \
-e GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/FILE_NAME.json \
-v $GOOGLE_APPLICATION_CREDENTIALS:/tmp/keys/FILE_NAME.json:ro \
gcr.io/PROJECT_ID/IMAGE
```

The GCP [docs](https://cloud.google.com/run/docs/building/containers) helped.

This doesn't seem to be an issue when using GKE since it automatically sets service account, so it's not an issue when deploying using the Makefile/current docs. Could be helpful to add a section to CONTRIBUTING.md.

**Comment by Daniel-Sanche** [comment]
Is there a reason you prefer development with Docker locally?

**Comment by gzhao408** [comment]
@Daniel-Sanche don't really have a preference, just wanted to try it out as an option - now that I have it working, it's faster than using `skaffold run` or the `make deploy` options and I can see all my logs immediately. This is the first time I've really used Docker 🤷 I'm not sure if it's a good idea but it hasn't seemed to be harmful so far.

**Comment by Daniel-Sanche** [comment]
This way certainly works! I'm hesitant to add it to the CONTRIBUTING file though, since deploying through Docker instead of Kubernetes could lead to some unexpected bugs, since it won't contain all the config set in the manifests (environment variables have to all be set manually, etc). I'm not sure if we should make it the recommended workflow

Ideally we would set up a skaffold development profile that deploys GCP credentials as secrets to each pod, so you can develop using Kubernetes entirely locally. But I'm not sure if that's worth the effort when using "make deploy" to GKE or using your Docker method also works

**Comment by gzhao408** [comment]
> since deploying through Docker instead of Kubernetes could lead to some unexpected bugs, since it won't contain all the config set in the manifests

Yeah that definitely makes sense.

**Comment by simonz130** [comment]
We could add it to contributing.md with the right context (i. e. - if you want to debug a single microservice code, you can do faster repeatable deployments locally using docker...)
